name: codecov

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    codecov:
        name: Test
        runs-on: ubuntu-20.04

        steps:
        -   uses: actions/setup-go@v4
            with:
                go-version: '1.21'
                cache: false
        -   uses: actions/checkout@v3

        -   name: Test
            run: go test -shuffle=on -race -coverprofile=coverage.txt -covermode=atomic ./...

        -   name: Vet
            run: go vet ./...

        -   name: Codecov
            run: bash <(curl -s https://codecov.io/bash)